version: '2'

networks:
  my-network:
    driver: bridge
services:
  openldap:
    container_name: oldp-srv
    image: bitnami/openldap:2
    ports:
      - '389:1389'
      - '636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_ROOT=dc=tsand,dc=org
      - LDAP_ADMIN_DN=cn=admin,dc=tsand,dc=org 
      - LDAP_ADD_SCHEMAS="yes"
      - LDAP_EXTRA_SCHEMAS="sudo"
    networks:
      - my-network
    volumes:
      - 'openldap_data:/bitnami/openldap'
      - ./ldifs:/ldifs
  phpldapadmin:
    container_name: oldp-mgmt
    image: osixia/phpldapadmin:0.9.0
    ports:
      - '6443:443'
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap.tsand.org
    networks:
      - my-network
  ssh-host:
    container_name: oldp-ssh
    image: ssh-host
    ports:
      - '2222:22'
    networks:
      - my-network
volumes:
  openldap_data:
    driver: local

